# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# No shadows for all non floating windows
windowrule = match:float false, no_shadow true

# Floating windows
windowrule = float true,match:class ^(firefox)$,match:title ^(Bild-im-Bild)$
windowrule = match:title Bluetooth Devices, float on
windowrule = match:title Network Connections, float on
windowrule = match:title satty, float on
windowrule = match:class nm-connection-editor, float on
windowrule = match:class org.gnome.Loupe, float on
windowrule = match:class xdg-desktop-portal-gtk, float on
windowrule = match:class nm-connection-editor, float on
windowrule = match:class org.gnome.NautilusPreviewer, float on

# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█

# SwayNC
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.1
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.6

# Screenshots
layerrule = no_anim on, match:namespace selection

# Vicinae
layerrule = blur on, match:namespace vicinae
layerrule = ignore_alpha 0.5, match:namespace vicinae
layerrule = no_anim on, match:namespace vicinae

# Ags
layerrule = blur on, match:namespace gtk4-layer-shell
layerrule = ignore_alpha 0.5, match:namespace gtk4-layer-shell
layerrule = blur_popups on, match:namespace gtk4-layer-shell

