[config.wallpaper]
set = false
command = ""

[templates.hyprpaper]
input_path = "./templates/hyprpaper.conf"
output_path = "~/.config/hypr/hyprpaper.conf"
post_hook = "pkill hyprpaper && nohup hyprpaper &>/dev/null &"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = """
sh -c '
  pkill swaync && nohup swaync &>/dev/null &
  ags quit || nohup ags run ~/.config/ags/app.tsx &>/dev/null &
  '
"""

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Documents/Notizen/.obsidian/themes/Material/theme.css'

[templates.ghostty]
input_path = "./templates/ghostty.conf"
output_path = "~/.config/ghostty/config"

[templates.vscode]
input_path = './templates/vscode.json'
output_path = '~/.vscode/extensions/material-3/themes/Material 3-color-theme.json'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/material.toml'
post_hook = 'vicinae theme set material'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/themes/colors.conf'
post_hook = 'hyprctl reload >/dev/null 2>&1'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
