[config.wallpaper]
set = false
command = ""

[templates.hyprpaper]
input_path = "./templates/hyprpaper.conf"
output_path = "~/.config/dynamic-theming/hyprpaper.conf"
post_hook = "pkill hyprpaper && nohup hyprpaper &>/dev/null &"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = """
sh -c 'pkill swaync && nohup swaync &>/dev/null &'
"""

[templates.obsidian]
input_path = './templates/obsidian.css'
output_path = '~/Documents/Notizen/.obsidian/themes/Material/theme.css'

[templates.ghostty]
input_path = "./templates/ghostty.conf"
output_path = "~/.config/ghostty/config"

# [templates.spotify]
# input_path = './templates/spotify.ini'
# output_path = '~/.config/spicetify/Themes/material3/color.ini'
# post_hook = 'spicetify apply -q -n'

# [templates.sddm]
# input_path = './templates/sddm-theme.conf'
# output_path = '/usr/share/sddm/themes/Candy/theme.conf'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/dynamic-theming/colors.conf'
post_hook = 'hyprctl reload >/dev/null 2>&1'
