$image = /home/paul/Bilder/Wallpapers/material_pastel_8.jpg

$background = rgba(12140dff)

$error = rgba(ffb4abff)

$error_container = rgba(c32220ff)

$inverse_on_surface = rgba(303129ff)

$inverse_primary = rgba(4c5e1eff)

$inverse_surface = rgba(e3e3d7ff)

$on_background = rgba(e3e3d7ff)

$on_error = rgba(580003ff)

$on_error_container = rgba(ffffffff)

$on_primary = rgba(202c00ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(161f00ff)

$on_primary_fixed_variant = rgba(3b4b0dff)

$on_secondary = rgba(242a14ff)

$on_secondary_container = rgba(ffffffff)

$on_secondary_fixed = rgba(181e09ff)

$on_secondary_fixed_variant = rgba(424830ff)

$on_surface = rgba(e8e8dbff)

$on_surface_variant = rgba(c6c8b8ff)

$on_tertiary = rgba(002e28ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(00201cff)

$on_tertiary_fixed_variant = rgba(1f4d46ff)

$outline = rgba(969889ff)

$outline_variant = rgba(636659ff)

$primary = rgba(bacf82ff)

$primary_container = rgba(596b2aff)

$primary_fixed = rgba(d6eb9cff)

$primary_fixed_dim = rgba(bacf82ff)

$scrim = rgba(000000ff)

$secondary = rgba(c3caaaff)

$secondary_container = rgba(61674cff)

$secondary_fixed = rgba(dfe6c4ff)

$secondary_fixed_dim = rgba(c3caaaff)

$shadow = rgba(000000ff)

$source_color = rgba(56603bff)

$surface = rgba(12140dff)

$surface_bright = rgba(3d3e36ff)

$surface_container = rgba(22241cff)

$surface_container_high = rgba(2d2e26ff)

$surface_container_highest = rgba(383931ff)

$surface_container_low = rgba(1b1d16ff)

$surface_container_lowest = rgba(0b0c06ff)

$surface_dim = rgba(12140dff)

$surface_tint = rgba(bacf82ff)

$surface_variant = rgba(45483cff)

$tertiary = rgba(a1d0c7ff)

$tertiary_container = rgba(3f6c65ff)

$tertiary_fixed = rgba(bcece2ff)

$tertiary_fixed_dim = rgba(a1d0c7ff)
